---
# install k8s packages
- name: Common setup.
  include: install_k8s_packages.yml

# memory settings
- name: Common setup.
  include: memory_setup.yml

# Provision Master
- name: Check if Kubernetes has already been initialized.
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: Provision master if not installed yet
  include: master-provisioning.yml
  when: "'master' in group_names and not kubernetes_init_stat.stat.exists"

# Provision Workers
- name: Sotre k8s token and hash to dummy host
  include: store_info_to_join.yml
  when: "'master' in group_names"

- name: Provision workers
  include: workers-provisioning.yml
  when: "'workers' in group_names"
