apiVersion: apps/v1
kind: Deployment
metadata:
  name: scd30
spec:
  selector:
    matchLabels:
       role: app
  replicas: 2
  template:
    metadata:
      labels:
         role: app
    spec:
      containers:
      - name: scd30-container
        volumeMounts:
        - mountPath: /dev/i2c-1
          name: i2c
        securityContext:
          privileged: true
        image: akihirodive/raspi-k8s:v1.0 
        imagePullPolicy: Always
        ports:
        - containerPort: 1000
          hostPort: 1000
      volumes:
      - name: i2c
        hostPath:
          path: /dev/i2c-1
